# This file define the controllers of the joints
# For each of them there is a adjustable PID

rrbot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_12
    pid: {p: 0.25, i: 0.2, d: 0.4}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_23
    pid: {p: 10.0, i: 0.01, d: 10.0}
